# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b2b3405a16c1416b70ff8dcb348c6501521f94d771e00021992bfe17d5b32447f3f45e421215b28d09f5f1198b6337dfd2f02cd0a3ff2fd36e38cbb2fc0974

test:
  secret_key_base: d1a0ab176ec09425cf3176eb04234796e00fd93acc7cd0afa4ebfbaeed79177b127da0d83419cb41bfe9825022325e533f2bdc85a384f8a8302d630ad6f6b774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
